# Generated by Django 2.1.1 on 2019-04-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_AdminUser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nickname',
        ),
    ]
